version: '3.7'
services:
  db:
    container_name: scalerr-api-db
    image: postgres:12-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

volumes:
  db_data:
